export { GreetingIcon } from "./greeting";
export { PrintIcon } from "./print";
export { PrintIcon2 } from "./print-2";
export { UserIcon } from "./user";
export { FolderIcon } from "./folder";
export { CardBoardIcon } from "./cardboard";
export { PaintIcon } from "./paint";
export { CompassIcon } from "./compass";
export { TaskIcon } from "./task";
export { ChevronRigthIcon } from "./chevronRightIcon";
export { EditIcon } from "./edit";
export { RulerIcon } from "./ruler";
export { CloseIcon } from "./closeIcon";
export { DeleteUserIcon } from "./delete-user-icon"
export { DetailsIcon } from "./details-icon"
export { UpdateIcon } from "./update-icon"
export { OptionsIcon } from "./options-icon"
export { DeleteShapeIcon } from "./delete-shape-icon"
export { LogIcon } from "./log-icon"