import type { Metadata } from "next";
import { Inter, Raleway, Montserrat, Poppins } from "next/font/google";
import { SideBarProvider } from "@/context/sidebar.context";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-raleway",
});

const montserat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-montserat",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "NOUVELLE - MICI",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/assets/logo/sig-variant.png"
          type="image/x-icon"
        />
      </head>
      <body
        className={`${inter.className} ${raleway.variable} ${montserat.variable} ${poppins.variable}`}
      >
        <SideBarProvider>{children}</SideBarProvider>
      </body>
    </html>
  );
}
